<?php

/**
 * @file
 * Contains d8_toptrumps01.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_toptrumps01_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_toptrumps01 module.
    case 'help.page.d8_toptrumps01':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 TopTrumps01 test d8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8_toptrumps01_theme() {
  return [
    'd8_toptrumps01' => [
      'render element' => 'children',
    ],
  ];
}



function d8_toptrumps01_install() {

    $entity_manager = \Drupal::entityManager();
    $entity_storage_top_trumps_fields   = $entity_manager->getStorage('top_trumps_fields_entity');
    $entity_storage_top_trumps_cards    = $entity_manager->getStorage('top_trumps_cards_entity');
    $entity_storage_top_trumps_category = $entity_manager->getStorage('top_trumps_category_entity');


    $arr_categories = array();
    $arr_categories[] = array("name"=> "category01" );
    $arr_categories[] = array("name"=> "category02" );

    foreach ($arr_categories as $key => $value) {
        $entity_object = $entity_storage_top_trumps_category->create($value);
        $entity_storage_top_trumps_category->save($entity_object);
        //$created_regions_ids[] = $entity_object->id();
    }


    $arr_fields = array();
    $arr_fields[] = array("name"=> "Loyalty",      "comparison"=> ">",      "category_id"=> "1" );
    $arr_fields[] = array( "name"=> "Agility",      "comparison"=> ">",      "category_id"=> "1");
    $arr_fields[] = array("name"=> "Cuddliness",      "comparison"=> ">",      "category_id"=> "1");
    $arr_fields[] = array("name"=> "Appetite",      "comparison"=> "<" ,      "category_id"=> "1");


    //$arr_fields[] = array('name'=>'ΔΙΕΥΘΥΝΣΗ Δ.Ε. ΔΡΑΜΑΣ', 'registryno'=>'0900115');
    //$arr_fields[] = array('name'=>'ΔΙΕΥΘΥΝΣΗ Δ.Ε. ΦΩΚΙΔΑΣ', 'registryno'=>'4800115');

    foreach ($arr_fields as $key => $value) {
        $entity_object = $entity_storage_top_trumps_fields ->create($value);
        $entity_storage_top_trumps_fields ->save($entity_object);
        //$created_regions_ids[] = $entity_object->id();
    }


    $arr_cards = array();


    $arr_cards[] = array("name"=> "Angel", "image" => "assets/top-trumps-cats-angel.jpg", "fields_values" => '[8, 6, 5, 2]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Bastet", "image" => "assets/top-trumps-cats-bastet.jpg", "fields_values" => '[6, 7, 4, 4]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Bull", "image" => "assets/top-trumps-cats-bull.jpg", "fields_values" => '[8, 6, 3, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Clark", "image" => "assets/top-trumps-cats-clark.jpg", "fields_values" => '[10, 5, 2, 4]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Cuddles", "image" => "assets/top-trumps-cats-cuddles.jpg", "fields_values" => '[7, 5, 10, 6]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Cutie", "image" => "assets/top-trumps-cats-cutie.jpg", "fields_values" => '[7, 4, 9, 6]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Daisy", "image" => "assets/top-trumps-cats-daisy.jpg", "fields_values" => '[2, 7, 5, 2]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Donut", "image" => "assets/top-trumps-cats-donut.jpg", "fields_values" => '[4, 3, 3, 10]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Firefly", "image" => "assets/top-trumps-cats-firefly.jpg", "fields_values" => '[6, 9, 4, 3]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Flabber", "image" => "assets/top-trumps-cats-flabber.jpg", "fields_values" => '[7, 1, 6, 8]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Furry", "image" => "assets/top-trumps-cats-furry.jpg", "fields_values" => '[7, 4, 6, 3]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Grumpy", "image" => "assets/top-trumps-cats-grumpy.jpg", "fields_values" => '[6, 4, 1, 5]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Hunky Hank", "image" => "assets/top-trumps-cats-hunky-hank.jpg", "fields_values" => '[6, 1, 6, 10]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Hunter", "image" => "assets/top-trumps-cats-hunter.jpg", "fields_values" => '[5, 10, 3, 8]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Jay", "image" => "assets/top-trumps-cats-jay.jpg", "fields_values" => '[8, 7, 5, 4]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Little Lion", "image" => "assets/top-trumps-cats-little-lion.jpg", "fields_values" => '[4, 10, 5, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Lynx", "image" => "assets/top-trumps-cats-lynx.jpg", "fields_values" => '[3, 8, 3, 5]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Nappy", "image" => "assets/top-trumps-cats-nappy.jpg", "fields_values" => '[5, 2, 5, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Owl", "image" => "assets/top-trumps-cats-owl.jpg", "fields_values" => '[2, 2, 1, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "P-Dog", "image" => "assets/top-trumps-cats-pdog.jpg", "fields_values" => '[7, 3, 2, 9]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Precious", "image" => "assets/top-trumps-cats-precious.jpg", "fields_values" => '[3, 7, 4, 1]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Rex", "image" => "assets/top-trumps-cats-rex.jpg", "fields_values" => '[10, 7, 3, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Rumble", "image" => "assets/top-trumps-cats-rumble.jpg", "fields_values" => '[4, 7, 2, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Scarface", "image" => "assets/top-trumps-cats-scarface.jpg", "fields_values" => '[7, 7, 6, 6]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Scratchy", "image" => "assets/top-trumps-cats-scratchy.jpg", "fields_values" => '[2, 4, 2, 7]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Sleeky", "image" => "assets/top-trumps-cats-sleeky.jpg", "fields_values" => '[5, 8, 5, 4]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Spencer", "image" => "assets/top-trumps-cats-spencer.jpg", "fields_values" => '[9, 3, 5, 6]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Swift", "image" => "assets/top-trumps-cats-swift.jpg", "fields_values" => '[2, 9, 6, 5]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Timi", "image" => "assets/top-trumps-cats-timi.jpg", "fields_values" => '[10, 5, 5, 4]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Tony", "image" => "assets/top-trumps-cats-tony.jpg", "fields_values" => '[6, 6, 4, 3]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "V", "image" => "assets/top-trumps-cats-v.jpg", "fields_values" => '[1, 9, 3, 1]' ,"category_id"=> "1" );
    $arr_cards[] = array("name"=> "Watson", "image" => "assets/top-trumps-cats-watson.jpg", "fields_values" => '[9, 3, 4, 6]' ,"category_id"=> "1" );

    foreach ($arr_cards as $key => $value) {
        $entity_object = $entity_storage_top_trumps_cards->create($value);
        $entity_storage_top_trumps_cards->save($entity_object);
        //$created_regions_ids[] = $entity_object->id();
    }


} // END of   function d8_toptrumps01_install() {



function d8_toptrumps01_uninstall() {
    //delete
    $entity_manager = \Drupal::entityManager();
    $entity_storage_top_trumps_fields   = $entity_manager->getStorage('top_trumps_fields_entity');
    $entity_storage_top_trumps_cards    = $entity_manager->getStorage('top_trumps_cards_entity');
    $entity_storage_top_trumps_category = $entity_manager->getStorage('top_trumps_category_entity');


    $all_top_trumps_fields = $entity_storage_top_trumps_fields->loadMultiple(NULL);
    $entity_storage_top_trumps_fields->delete($all_top_trumps_fields);


    $all_top_trumps_cards = $entity_storage_top_trumps_cards->loadMultiple(NULL);
    $entity_storage_top_trumps_cards->delete($all_top_trumps_cards);
    

    $all_top_trumps_category = $entity_storage_top_trumps_category->loadMultiple(NULL);
    $entity_storage_top_trumps_category->delete($all_top_trumps_category);



    

}  